Remove all dependencies, switch to hunter CMake package manager and provides a precompiled portable binary
rmcolq/pandora pull request #256
Opened 2021-01-11 23:14 UTC by leoisl

Sorry for this PR that is doing two things at the same time!

Main changes:
  * Now we use the [hunter](https://github.com/cpp-pm/hunter/) CMake package manager to install `ZLIB`, `GTest`, `GMock`, and `Boost`, thus we have no need to have these as preinstalled dependencies, or custom code to install them (`ext/gtest.cmake`, `ext/boost.cmake`, etc). GATB is the only external library we still need to install ourselves, with `ext/gatb.cmake`. All the rest is now managed by `hunter`;
  * Most notably, before we required the user to have `ZLIB` and `Boost 1.62.0` preinstalled. Now there is no dependencies anymore, just the very basic C++ compilation tools. As per the [docker image](https://github.com/rmcolq/pandora/blob/ecfff1ed312d0fa7b67364347b0c6e80c81c4c28/Dockerfile#L13), the required tools are only `build-essential`, `git`, `cmake` and `wget`. I think now it is really easy for users to build from source;
  * Adds a [script](https://github.com/rmcolq/pandora/tree/hunter/portable_binary_builder) that builds a cross-distro Linux binary for pandora using [Holy Build Box](http://phusion.github.io/holy-build-box/). The binary thus should work on pretty much any glibc-2.12-or-later-based x86 and x86-64 Linux distribution released since approx 2011, e.g.: Debian >= 7, Ubuntu >= 10.10, Red Hat Enterprise Linux >= 6, CentOS >= 6, etc. See https://github.com/rmcolq/pandora/tree/hunter#no-installation-needed---precompiled-portable-binary for more details on the precompiled portable binary;
  * For GATB to accept a non-system installation of ZLIB, I had to change its `CMakeLists.txt`. So I just did a branch of the v1.4.1 tag (the one we use), and made these few changes (see https://github.com/leoisl/gatb-core/commits/1.4.1_zlib);
  * Some other CMake refactorings;
  * Closes #254.

The hunter changes (i.e. no need for `ZLIB`/`Boost` dependencies to compile) works on local, and on the docker container, but I don't know if Travis CI build is working.

Precompiled binary works on local, I will soon test on several other linux distros (old ubuntu/debian/redhat/centos). Sorry, I still did not have time to do so, will do tomorrow.

Next up is https://github.com/rmcolq/pandora/issues/169 so that we can finally have proper `DEBUG` and `RELEASE` `pandora` builds. Then I think tooling/compilation will be in a better state.

2021-01-11 23:26 UTC, leoisl commented
@iqbal-lab I added you as a reviewer on this, but all I need is for you to review the [README.md](https://github.com/rmcolq/pandora/pull/256/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), if it is fine to leave like this, or if the precompiled binary sections is too long and should be simplified

2021-01-12 03:32 UTC, leoisl commented
Update: also closes https://github.com/rmcolq/pandora/issues/167

2021-01-12 03:44 UTC, mbhall88 requested changes
This is awesome Leandro!! Thank you - it must have been a pain to get this working.  

I have tested the installation process locally and it all works smoothly. I tried building the binary locally but the building of the docker image for holy build was taking forever so I gave up. But if you've done it that is good enough for me. I also downloaded and used the binary from your dropbox link ok too

2021-01-12 03:44 UTC, mbhall88 commented on README.md
> +  wget https://www.dropbox.com/s/74ptrnk4k5qcc6o/pandora-linux-precompiled_v0.8.0_beta?dl=1 -O pandora-linux-precompiled_v0.8.0_beta
```suggestion
  wget "https://www.dropbox.com/s/74ptrnk4k5qcc6o/pandora-linux-precompiled_v0.8.0_beta?dl=1" -O pandora-linux-precompiled_v0.8.0_beta
```

This failed for me without the quotes

2021-01-12 03:56 UTC, leoisl commented on README.md
> +- A Unix or Mac OS.
Decided to list all requirements and changed to:
> - A Unix or Mac OS, with a C++11 compiler toolset (e.g. `g++`, `ld`, `make`, `ctest`, etc), `cmake`, `git` and `wget`.

Does this look fine or is there sth we should add/remove?

2021-01-12 03:59 UTC, mbhall88 commented on README.md
> +- A Unix or Mac OS.
LFTM

2021-01-12 03:59 UTC, leoisl commented on portable_binary_builder/README.md
> +# Usage
I do agree if I understood correctly: we create a `docs` directory and add the [Usage.MD](https://github.com/rmcolq/pandora/wiki/Usage) there?

2021-01-12 04:07 UTC, mbhall88 commented on portable_binary_builder/README.md
> +# Usage
Well we have a directory called `doc` so maybe it can just go in there?

2021-01-12 04:17 UTC, leoisl commented on portable_binary_builder/README.md
> +# Usage
Fine by me, I thought that was a directory to contain `doxygen` stuff, like the `Doxyfile.in` file there... but I never generated docs in `pandora` using `doxygen`, so I actually don't know anything... let's put it there then!

2021-01-12 04:22 UTC, mbhall88 commented on portable_binary_builder/README.md
> +# Usage
Haha yeah, I know nothing about that either :shrug:

2021-01-12 04:25 UTC, leoisl commented on portable_binary_builder/README.md
> +# Usage
Done in https://github.com/rmcolq/pandora/pull/256/commits/5b02129082e6be970358819998dea8edb80bb1fa

2021-01-12 04:46 UTC, leoisl commented
> I tried building the binary locally but the building of the docker image for holy build was taking forever so I gave up.

Yep, it took almost 2 hours to build on my machine haha... their dockerhub hosted image is broken because Centos 6 reached EOL, and they have still old links to the repos... The tip of their github repo works, but we then need to build the image ourselves. I have the image built here, and it is always good to test on another machine. I can upload to my dockerhub and send to you, if you are willing to test.

> I also downloaded and used the binary from your dropbox link ok too

Yeah, I will still test this binary on ubuntu 10.10, debian 7.11, and Centos 6.

2021-01-12 04:59 UTC, leoisl commented on portable_binary_builder/build_portable_binary.sh
> +# Invokes phusion/holy-build-box-64:2.0.1 docker container to build portable pandora.
Done in https://github.com/rmcolq/pandora/pull/256/commits/a6b10044020369785335a23967a4bfe4fbd4fd5f

2021-01-12 04:59 UTC, leoisl commented on portable_binary_builder/build_portable_binary_core.sh
> +#!/bin/bash
Done in https://github.com/rmcolq/pandora/pull/256/commits/a6b10044020369785335a23967a4bfe4fbd4fd5f

2021-01-12 04:59 UTC, mbhall88 commented on portable_binary_builder/README.md
> +# Usage
Oh sorry I mean move this file there. I don't like have an extra directory called protable_binary_builder

2021-01-12 04:59 UTC, leoisl commented on portable_binary_builder/build_portable_binary.sh
> +sudo docker run -t -i --rm \
That is right, fixed in https://github.com/rmcolq/pandora/pull/256/commits/a6b10044020369785335a23967a4bfe4fbd4fd5f

2021-01-12 05:07 UTC, leoisl commented on portable_binary_builder/README.md
> +# Usage
Oops sorry, I think I made a mess now. I moved `portable_binary_builder` to the `scripts` folder (https://github.com/rmcolq/pandora/tree/hunter/scripts/portable_binary_builder). There we have the `README.md`. And I added the `pandora` usage to the `doc` folder (https://github.com/rmcolq/pandora/tree/hunter/doc). I guess this second one I misunderstood... Could you clarify what I missed?

2021-01-12 07:40 UTC, mbhall88 commented on portable_binary_builder/README.md
> +# Usage
That all sounds fine

2021-01-12 07:40 UTC, mbhall88 approved these changes

2021-01-12 12:37 UTC, leoisl commented on portable_binary_builder/README.md
> +# Usage
Is it? Just realised the `Usage` you meant was about the `portable_binary_builder/README.md`, I have no idea why I confused with the `Usage` in the main `README.md` :p well, tell me if there is sth I need to change!

2021-01-12 17:30 UTC, leoisl commented
Update:

I could not run the precompiled binary on Ubuntu 10.10 (from October 2010). As expected, it fails with:

```
./pandora-linux-precompiled_v0.8.0_beta: /usr/lib/libgomp.so.1: version `GOMP_4.0` not found (required by ./pandora-linux-precompiled_v0.8.0_beta)
```
i.e. OpenMP 4.0 was not found. I installed `g++` with `apt-get install g++`, but unfortunately for this ubuntu version, the gcc/g++ version is earlier than 4.9, so OpenMP 4.0 is not supported.

So, I tested on ubuntu 14.10 (from October 2014), and it worked right out of the box, no need to install anything! `gcc/g++ 4.9.1` comes already pre-installed, so everything worked, even the sample example.

Debian 7 (from March 2013) also did not work, but Debian 8 (from April 2015)  worked also right out of the box, no need to install anything! `gcc/g++` is not pre-installed on Debian 8, but OpenMP 4.0+ comes already pre-installed, so the sample example worked just fine.

I think I am satisfied with the compatibility of the precompiled binary. It is a shame that we still require OpenMP 4.0+ installed, but it seems to be a widely available library, and it won't be much trouble for the users.

@iqbal-lab and @mbhall88 , are you also satisfied or would you like further tests on earlier versions of RedHat or CentOS or another OS?

2021-01-12 17:32 UTC, iqbal-lab commented
i'm haapy

2021-01-13 01:36 UTC, mbhall88 commented
That is all awesome @leoisl. I think we are supporting the vast majority of users now with all the available options. Great work!

2021-01-13 03:44 UTC, leoisl commented
Great! Merging then! I guess we can then work towards https://github.com/rmcolq/pandora/issues/244 to provide another installation option!

2021-01-13 03:45 UTC, merged

2021-01-13 06:47 UTC, mbhall88 commented
> Great! Merging then! I guess we can then work towards #244 to provide another installation option!

and #166 and #169 would be good to get out of the way

2021-01-13 15:37 UTC, leoisl commented
Yeah, I am working on these now